//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "homework")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub hw_term: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub hw_ccode: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub hw_id: String,
    pub hw_week: i8,
    pub hw_chapter: i8,
    pub hw_filename: String,
    pub hw_description: String,
    pub hw_bdate: DateTime,
    pub hw_edate: DateTime,
    #[sea_orm(column_type = "Decimal(Some((5, 1)))")]
    pub hw_score: Decimal,
    pub hw_date_add: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::term::Entity",
        from = "Column::HwTerm",
        to = "super::term::Column::TermNo",
        on_update = "Cascade",
        on_delete = "NoAction"
    )]
    Term,
}

impl Related<super::term::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Term.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
