//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "log_post")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub log_post_id: i32,
    pub log_post_postid: Option<i32>,
    pub log_post_opno: String,
    pub log_post_ipaddr: Option<String>,
    pub log_post_date: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub log_post_comment: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::post::Entity",
        from = "Column::LogPostPostid",
        to = "super::post::Column::PostId",
        on_update = "Cascade",
        on_delete = "NoAction"
    )]
    Post,
    #[sea_orm(
        belongs_to = "super::student::Entity",
        from = "Column::LogPostOpno",
        to = "super::student::Column::StuNo",
        on_update = "Cascade",
        on_delete = "NoAction"
    )]
    Student,
}

impl Related<super::post::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Post.def()
    }
}

impl Related<super::student::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Student.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
