//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub mod prelude;

pub mod course;
pub mod homework;
pub mod homework_uploaded;
pub mod log_homework;
pub mod log_homework_uploaded;
pub mod log_login;
pub mod log_post;
pub mod log_rstpwd;
pub mod post;
pub mod sea_orm_active_enums;
pub mod student;
pub mod tag;
pub mod term;
