//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::course::Entity as Course;
pub use super::homework::Entity as Homework;
pub use super::homework_uploaded::Entity as HomeworkUploaded;
pub use super::log_homework::Entity as LogHomework;
pub use super::log_homework_uploaded::Entity as LogHomeworkUploaded;
pub use super::log_login::Entity as LogLogin;
pub use super::log_post::Entity as LogPost;
pub use super::log_rstpwd::Entity as LogRstpwd;
pub use super::post::Entity as Post;
pub use super::student::Entity as Student;
pub use super::tag::Entity as Tag;
pub use super::term::Entity as Term;
