//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "hwup_is_del")]
pub enum HwupIsDel {
    #[sea_orm(string_value = "0")]
    _0,
    #[sea_orm(string_value = "1")]
    _1,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "post_is_del")]
pub enum PostIsDel {
    #[sea_orm(string_value = "0")]
    _0,
    #[sea_orm(string_value = "1")]
    _1,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "post_tag_01")]
pub enum PostTag01 {
    #[sea_orm(string_value = "0")]
    _0,
    #[sea_orm(string_value = "1")]
    _1,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "post_tag_02")]
pub enum PostTag02 {
    #[sea_orm(string_value = "0")]
    _0,
    #[sea_orm(string_value = "1")]
    _1,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "post_tag_03")]
pub enum PostTag03 {
    #[sea_orm(string_value = "0")]
    _0,
    #[sea_orm(string_value = "1")]
    _1,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "post_tag_04")]
pub enum PostTag04 {
    #[sea_orm(string_value = "0")]
    _0,
    #[sea_orm(string_value = "1")]
    _1,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "post_tag_05")]
pub enum PostTag05 {
    #[sea_orm(string_value = "0")]
    _0,
    #[sea_orm(string_value = "1")]
    _1,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "post_tag_06")]
pub enum PostTag06 {
    #[sea_orm(string_value = "0")]
    _0,
    #[sea_orm(string_value = "1")]
    _1,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "post_tag_07")]
pub enum PostTag07 {
    #[sea_orm(string_value = "0")]
    _0,
    #[sea_orm(string_value = "1")]
    _1,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "post_tag_08")]
pub enum PostTag08 {
    #[sea_orm(string_value = "0")]
    _0,
    #[sea_orm(string_value = "1")]
    _1,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "post_tag_09")]
pub enum PostTag09 {
    #[sea_orm(string_value = "0")]
    _0,
    #[sea_orm(string_value = "1")]
    _1,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "post_tag_10")]
pub enum PostTag10 {
    #[sea_orm(string_value = "0")]
    _0,
    #[sea_orm(string_value = "1")]
    _1,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "post_type")]
pub enum PostType {
    #[sea_orm(string_value = "Question")]
    Question,
    #[sea_orm(string_value = "QuestionsAdditional")]
    QuestionsAdditional,
    #[sea_orm(string_value = "Answer")]
    Answer,
    #[sea_orm(string_value = "Other")]
    Other,
    #[sea_orm(string_value = "/")]
    U002F,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "stu_cno_1_is_del")]
pub enum StuCno1IsDel {
    #[sea_orm(string_value = "0")]
    _0,
    #[sea_orm(string_value = "1")]
    _1,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "stu_cno_2_is_del")]
pub enum StuCno2IsDel {
    #[sea_orm(string_value = "0")]
    _0,
    #[sea_orm(string_value = "1")]
    _1,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "stu_cno_3_is_del")]
pub enum StuCno3IsDel {
    #[sea_orm(string_value = "0")]
    _0,
    #[sea_orm(string_value = "1")]
    _1,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "stu_enable")]
pub enum StuEnable {
    #[sea_orm(string_value = "0")]
    _0,
    #[sea_orm(string_value = "1")]
    _1,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "stu_is_del")]
pub enum StuIsDel {
    #[sea_orm(string_value = "0")]
    _0,
    #[sea_orm(string_value = "1")]
    _1,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "stu_sex")]
pub enum StuSex {
    #[sea_orm(string_value = "男")]
    U7537,
    #[sea_orm(string_value = "女")]
    U5973,
    #[sea_orm(string_value = "/")]
    U002F,
}
